# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BirminhamTrains' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  pod 'TwitterKit'
  pod 'Firebase/Core'

  target 'BirminhamTrainsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BirminhamTrainsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
